# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'acc', 'eif-acc-web'), (b'aci', 'eif-accing-web'), (b'cas', 'eif-cashier-web'), (b'cms', 'eif-cms'), (b'contract', 'eif-contract-web'), (b'cweb', 'eif-customer-website'), (b'fds', 'eif-fds-web'), (b'fdsb', 'eif-fds-bridge-web'), (b'fdsjob', 'eif-fds-job'), (b'fis', 'eif-fis-web'), (b'fisjob', 'eif-fis-job'), (b'ftc', 'eif-ftc-web'), (b'ftcjob', 'eif-ftc-job'), (b'gotong', 'eif-gotong-web'), (b'mkt', 'eif-market-web'), (b'mktweb', 'eif-market-website'), (b'mbr', 'eif-member-web'), (b'mob', 'eif-mobile-website'), (b'mtp', 'eif-mtp-web'), (b'ofc', 'eif-ofc-web'), (b'omc', 'eif-omc-web'), (b'pc', 'eif-paycore-web'), (b'pcf', 'eif-paycore-frontedge-web'), (b'pcjob', 'eif-paycore-job'), (b'risk', 'eif-risk-web'), (b'setting', 'eif-setting-web'), (b'transcore', 'eif-transcore-web'), (b'vat', 'eif-verify-accounting-web')], max_length=32, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('deploy_time', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('version', models.CharField(max_length=50, verbose_name='git version')),
                ('description', models.TextField(blank=True, null=True, verbose_name='desc')),
                ('db', models.TextField(blank=True, default=b'\xe5\x90\xa6')),
                ('disconf', models.TextField(blank=True, default=b'\xe5\x90\xa6')),
                ('lts', models.TextField(blank=True, default=b'\xe5\x90\xa6')),
                ('mq', models.TextField(blank=True, default=b'\xe5\x90\xa6')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u4e0a\u7ebf\u53d1\u5e03',
                'verbose_name_plural': '\u4e0a\u7ebf\u53d1\u5e03',
            },
        ),
    ]
